/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ["class"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#131313",
        foreground: "#e5e2e1",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#a4cece",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#494900",
        "primary-fixed-dim": "#cdcd00",
        "inverse-on-surface": "#313030",
        secondary: "#cccc63",
        "on-surface": "#e5e2e1",
        "on-secondary": "#323200",
        surface: "#131313",
        "on-secondary-fixed": "#1d1d00",
        "on-tertiary-container": "#436b6c",
        primary: {
          DEFAULT: "#ffffff",
          foreground: "#323200",
        },
        "on-primary-container": "#686800",
        "on-primary-fixed": "#1d1d00",
        "on-error": "#690005",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#494900",
        tertiary: "#ffffff",
        "primary-container": "#eaea00",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed-variant": "#244d4e",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#201f1f",
        "on-tertiary": "#093637",
        "primary-fixed": "#eaea00",
        outline: "#939277",
        "on-tertiary-fixed": "#002020",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#484831",
        "on-primary": "#323200",
        "tertiary-fixed": "#c0eaeb",
        "tertiary-container": "#c0eaeb",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#cac8aa",
        "on-background": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#626200",
        "secondary-fixed": "#e8e87c",
        "secondary-container": "#676700",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "surface-tint": "#cdcd00",
        "secondary-fixed-dim": "#cccc63",
        "on-secondary-container": "#e6e67a",
        sidebar: {
          DEFAULT: "#131313",
          foreground: "#e5e2e1",
          primary: "#eaea00",
          "primary-foreground": "#1d1d00",
          accent: "#201f1f",
          "accent-foreground": "#ffffff",
          border: "#1c1b1b",
          ring: "#eaea00",
        },
      },
      borderRadius: {
        xl: "0.5rem",
        lg: "0.25rem",
        md: "0.1875rem",
        sm: "0.125rem",
        DEFAULT: "0.125rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "sans-serif"],
        technical: ["var(--font-technical)", "monospace"],
        body: ["var(--font-sans)", "sans-serif"],
        label: ["var(--font-sans)", "sans-serif"],
        sans: ["var(--font-sans)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
