const BaseTool = require('./baseTool');
const { getServiceDetailsTool } = require('../getServiceDetailsTool');

class PricingTool extends BaseTool {
    constructor() {
        super();
        this.description = 'Cek harga, durasi, dan SOP layanan (Repaint, Detailing, Coating)';
        this.capability = 'pricing';
    }

    async _run(parameters, state) {
        // Fallback to knownFacts if parameters are empty
        const knownFacts = state.consultation?.knownFacts || {};
        const vehicle = state.vehicle || {};
        
        const requestedServices = state.consultation?.requestedServices || [];
        // Priority: explicit params → requestedServices (captures latest user intent) → knownFacts fallback
        let rawServiceName = parameters.service_name || parameters.service || parameters.partToRepaint;
        if (!rawServiceName && requestedServices.length > 0) {
            // Use requestedServices — contains all services user has mentioned including the latest one
            rawServiceName = requestedServices;
        } else if (!rawServiceName) {
            // Last resort: use the first known service from state
            rawServiceName = knownFacts.partToRepaint?.value;
        }
        if (!rawServiceName) {
            rawServiceName = 'Repaint Bodi Halus';
        }
        let serviceNameArray = Array.isArray(rawServiceName) ? rawServiceName : [rawServiceName];

        // Business Rule Expansion BEFORE normalization:
        // "full bodi" = Repaint Bodi Halus + Repaint Bodi Kasar
        // "full bodi halus" = Repaint Bodi Halus only
        const expandedServices = [];
        for (const s of serviceNameArray) {
            if (typeof s === 'string') {
                const sLower = s.toLowerCase();
                if ((sLower.includes('full bodi') || sLower.includes('full body')) && !sLower.includes('halus')) {
                    // full bodi = dua layanan
                    expandedServices.push('Repaint Bodi Halus', 'Repaint Bodi Kasar');
                } else if (sLower.includes('full bodi halus')) {
                    expandedServices.push('Repaint Bodi Halus');
                } else {
                    expandedServices.push(s);
                }
            } else {
                expandedServices.push(s);
            }
        }
        serviceNameArray = [...new Set(expandedServices)];

        // Automatically fetch prices for upsells generated by the rule engine
        if (state.business?.upsells && Array.isArray(state.business.upsells)) {
            state.business.upsells.forEach(upsell => {
                if (upsell.service && !serviceNameArray.includes(upsell.service)) {
                    serviceNameArray.push(upsell.service);
                }
            });
        }

        // Normalize services and ensure "Repaint" prefix for known parts
        serviceNameArray = serviceNameArray.map(s => {
            if (typeof s === 'string') {
                let sLower = s.toLowerCase();
                
                // Do not touch other primary categories
                if (sLower.includes('detailing') || sLower.includes('coating') || sLower.includes('poles') || sLower.includes('cuci')) {
                    return s;
                }

                // If it's a repaint or an unknown part
                if (sLower.includes('repaint')) {
                    if (['bodi halus', 'bodi kasar', 'velg', 'cvt', 'arm'].some(p => sLower.includes(p))) {
                        return s; // it's a known repaint package
                    }
                    return 'Repaint Bodi Halus'; // Unknown repaint part -> default to Bodi Halus
                } else {
                    if (['velg', 'bodi halus', 'bodi kasar', 'cvt', 'arm'].some(part => sLower.includes(part))) {
                        return `Repaint ${s}`;
                    }
                    // If it doesn't have 'repaint' and isn't detailing/coating, assume it's a raw part name
                    return 'Repaint Bodi Halus';
                }
            }
            return s;
        });

        // Validation block: Prevent premature tool calls for Repaint
        const isRepaint = serviceNameArray.some(s => typeof s === 'string' && s.toLowerCase().includes('repaint'));
        const partToRepaintStr = serviceNameArray.find(s => typeof s === 'string' && s.toLowerCase().includes('repaint')) || '';
        let partToRepaint = parameters.partToRepaint;
        if (isRepaint && !partToRepaint) {
            if (partToRepaintStr.toLowerCase().includes('halus')) partToRepaint = 'bodi halus';
            else if (partToRepaintStr.toLowerCase().includes('kasar')) partToRepaint = 'bodi kasar';
            else if (partToRepaintStr.toLowerCase().includes('velg')) partToRepaint = 'velg';
            else if (partToRepaintStr.toLowerCase().includes('full')) partToRepaint = 'full bodi';
        }

        // Juga cek dari requestedServices jika partToRepaint masih null
        if (isRepaint && !partToRepaint) {
            const fullBodiService = requestedServices.find(s => typeof s === 'string' && s.toLowerCase().includes('full'));
            if (fullBodiService) partToRepaint = 'full bodi';
        }

        if (isRepaint && !partToRepaint) {
            return { error: "Missing parameter: partToRepaint. Tolong pastikan bagian motor yang ingin dicat (bodi halus, bodi kasar, velg, full bodi) sudah diketahui sebelum mengecek harga." };
        }

        // V1 implementation mapping
        // We pass arguments as required by V1 implementation: implementation({ service_name, motor_model, size, color_name })
        const motor_model = parameters.motor_model || parameters.motorModel || parameters.motor || knownFacts.motor?.value || vehicle.model?.value || vehicle.model || 'NMax';
        const size = parameters.size || parameters.motorSize;
        const color_name = parameters.color_name || parameters.paintColor || parameters.color || knownFacts.paintColor?.value || vehicle.paintType?.value;

        const toolResponse = await getServiceDetailsTool.implementation({
            service_name: serviceNameArray,
            motor_model,
            size,
            color_name
        });

        // getServiceDetailsTool wraps result in { success, data: actual_pricing, metadata, error, executionTimeMs }
        // Unwrap at source so processResult and extractCartItems both see actual pricing keys directly
        const resultString = toolResponse.data || toolResponse;

        // Format the raw JSON into a clean string so the Composer doesn't hallucinate
        let formattedText = "";
        
        try {
            const processResult = (res) => {
                let text = "";
                if (res.message) text += `${res.message}\n`;
                if (res.candidates && Array.isArray(res.candidates)) {
                    res.candidates.forEach(c => {
                        text += `- ${c.name}: ${c.price_formatted}\n`;
                        if (c.summary) text += `  Keterangan: ${c.summary}\n`;
                        if (c.description) text += `  Detail:\n${c.description}\n`;
                        if (c.note) text += `  Catatan: ${c.note}\n`;
                        if (c.estimated_duration) text += `  Estimasi waktu: ${c.estimated_duration}\n`;
                    });
                } else if (res.price_formatted) {
                    text += `- ${res.name || res.service_name}: ${res.price_formatted}\n`;
                    if (res.summary) text += `  Keterangan: ${res.summary}\n`;
                    if (res.description) text += `  Detail:\n${res.description}\n`;
                    if (res.estimated_duration) text += `  Estimasi waktu: ${res.estimated_duration}\n`;
                }
                return text;
            };

            if (resultString.multiple_services_requested && Array.isArray(resultString.results)) {
                formattedText = resultString.results.map(processResult).join('\n');
            } else {
                formattedText = processResult(resultString);
            }
        } catch (e) {
            console.error('[PricingTool] Failed to format result:', e);
            formattedText = "Gagal memformat harga, silakan cek manual.";
        }

        return {
            rawText: resultString,
            formattedText: formattedText,
            service: serviceNameArray.join(', ')
        };
    }
}

module.exports = new PricingTool();
